In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris_data=load_iris()

In [4]:
iris = pd.DataFrame(iris_data.data, columns=iris_data.feature_names)
iris['target'] = iris_data.target

In [5]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [7]:
x = iris_data.data 
y = iris_data.target 

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size =0.2, 
                                                    random_state = 0) 
   
print("xtrain shape : ", xtrain.shape) 
print("xtest shape  : ", xtest.shape) 
print("ytrain shape : ", ytrain.shape) 
print("ytest shape  : ", ytest.shape)

xtrain shape :  (120, 4)
xtest shape  :  (30, 4)
ytrain shape :  (120,)
ytest shape  :  (30,)


In [8]:
lr =  LogisticRegression()
lr.fit(xtrain, ytrain)
y_pred = lr.predict(xtest)

C:\Users\surabhi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\surabhi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


In [10]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix

In [11]:
print('Accuracy score: ', format(accuracy_score(ytest, y_pred)))
print('Precision score: ', format(precision_score(ytest, y_pred, average='micro')))
print('Recall score: ', format(recall_score(ytest, y_pred, average='micro')))
print('F1 score: ', format(f1_score(ytest, y_pred, average='micro')))
print('\nConfusion Matrix :\n', confusion_matrix(ytest, y_pred))

Accuracy score:  0.9666666666666667
Precision score:  0.9666666666666667
Recall score:  0.9666666666666667
F1 score:  0.9666666666666667

Confusion Matrix :
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [12]:
from sklearn.linear_model import Ridge
clf = Ridge(alpha=1.0)
clf.fit(xtrain, ytrain)
y_pred = lr.predict(xtest)

In [13]:
print('Accuracy score: ', format(accuracy_score(ytest, y_pred)))
print('Precision score: ', format(precision_score(ytest, y_pred, average='micro')))
print('Recall score: ', format(recall_score(ytest, y_pred, average='micro')))
print('F1 score: ', format(f1_score(ytest, y_pred, average='micro')))
print('\nConfusion Matrix :\n', confusion_matrix(ytest, y_pred))

Accuracy score:  0.9666666666666667
Precision score:  0.9666666666666667
Recall score:  0.9666666666666667
F1 score:  0.9666666666666667

Confusion Matrix :
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]
